addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.2")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"             % "1.0.0")
addSbtPlugin("au.com.onegeek"            %% "sbt-dotenv"         % "2.1.204")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.30")